module.exports = {
  apps: [
    {
      name: 'SAC-BRAIN-V14.0',
      script: './sipoma_autonomous.py',
      cwd: '/home/rog/ai-commander',
      interpreter: '/home/rog/ai-commander/venv/bin/python3',
      env: {
        NODE_ENV: 'production',
        XAI_API_KEY: process.env.XAI_API_KEY,
        TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN,
        CHAT_ID: process.env.CHAT_ID,
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      log_file: '/home/rog/ai-commander/logs/sac-brain.log',
      error_file: '/home/rog/ai-commander/logs/sac-brain-error.log',
      out_file: '/home/rog/ai-commander/logs/sac-brain-out.log',
      time: true,
      watch: false,
    },
    {
      name: 'SAC-BOT-V14.0',
      script: './ai_commander.py',
      cwd: '/home/rog/ai-commander',
      interpreter: '/home/rog/ai-commander/venv/bin/python3',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '200M',
      log_file: '/home/rog/ai-commander/logs/sac-bot.log',
      error_file: '/home/rog/ai-commander/logs/sac-bot-error.log',
      time: true,
    },
    {
      name: 'SAC-MONITOR-V14.0',
      script: './realtime_monitor.py',
      cwd: '/home/rog/ai-commander',
      interpreter: '/home/rog/ai-commander/venv/bin/python3',
      args: 'monitor',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '5s',
      max_memory_restart: '100M',
      log_file: '/home/rog/ai-commander/logs/sac-monitor.log',
      error_file: '/home/rog/ai-commander/logs/sac-monitor-error.log',
      time: true,
    },
    {
      name: 'SAC-TICK-V14.0',
      script: './tick_historian.py',
      cwd: '/home/rog/ai-commander',
      interpreter: '/home/rog/ai-commander/venv/bin/python3',
      args: 'sync',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '0 */6 * * *', // Sync every 6 hours
      autorestart: true,
      max_restarts: 3,
      min_uptime: '30s',
      max_memory_restart: '150M',
      log_file: '/home/rog/ai-commander/logs/sac-tick.log',
      error_file: '/home/rog/ai-commander/logs/sac-tick-error.log',
      time: true,
    },
  ],
};
