#!/usr/bin/env python3
"""
SAC-MONITOR-V13.1: The Guardian
- 1s High-Frequency Monitoring Loop
- Dynamic Trailing SL, Breakeven, Reversal Exit
- Emergency Exit on EMA21 M15 Breach
"""

import os
import time
import logging
import re
from datetime import datetime
import asyncio
from dotenv import load_dotenv

load_dotenv()

# CONFIG
MT4_FILES = '/home/rog/.wine/drive_c/Program Files (x86)/MetaTrader 4/MQL4/Files'
ACCOUNT_STATS_PATH = os.path.join(MT4_FILES, 'account_stats.txt')
MODIFY_ORDERS_PATH = os.path.join(MT4_FILES, 'modify_orders.txt')
CLOSE_ORDERS_PATH = os.path.join(MT4_FILES, 'close_orders.txt')
PRICE_DATA_PATH = os.path.join(MT4_FILES, 'price_data.txt')
EMA_DATA_PATH = os.path.join(MT4_FILES, 'ema_m15.txt')  # Generated by BRAIN

TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
CHAT_ID = os.getenv('CHAT_ID')

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - MONITOR - %(message)s',
    handlers=[
        logging.FileHandler('/home/rog/ai-commander/logs/sac-monitor.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class SACMonitor:
    def __init__(self):
        self.positions = {}
        self.last_sl_update = {}
        self.daily_peak_equity = 0
        
    async def send_telegram(self, msg):
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                await client.post(
                    f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage",
                    json={"chat_id": CHAT_ID, "text": f"🛡️ *SAC-MONITOR*\n{msg}", "parse_mode": "Markdown"}
                )
        except Exception as e:
            logger.error(f"Telegram failed: {e}")

    def parse_account_stats(self):
        try:
            with open(ACCOUNT_STATS_PATH, 'r') as f:
                line = f.read().strip()
                parts = line.split('|')
                if len(parts) >= 2:
                    balance, equity = float(parts[0]), float(parts[1])
                    self.daily_peak_equity = max(self.daily_peak_equity, equity)
                    return balance, equity
        except:
            pass
        return 0, 0

    def parse_positions(self, stats_line):
        """Parse open positions from account_stats.txt extended format"""
        positions = {}
        try:
            # Expected: Balance|Equity|Margin|...|POSITIONS:PAIR1:TYPE:ENTRY:SL:TP|PAIR2...
            if ':POSITIONS:' in stats_line:
                pos_data = stats_line.split(':POSITIONS:')[1]
                for pos_str in pos_data.split('|'):
                    if ':' in pos_str and len(pos_str.split(':')) >= 5:
                        pair, pos_type, entry, sl, tp = pos_str.split(':')[:5]
                        positions[pair] = {
                            'type': pos_type,
                            'entry': float(entry),
                            'sl': float(sl),
                            'tp': float(tp)
                        }
        except:
            pass
        self.positions = positions
        return positions

    def parse_price_data(self):
        """Get latest prices for trailing calc"""
        try:
            with open(PRICE_DATA_PATH, 'r') as f:
                line = f.read().strip()
                pair, tf, _, o, h, l, c, v = line.split('|')
                return float(c), float(h), float(l)
        except:
            return 0, 0, 0

    def calculate_pips(self, pair, price1, price2):
        """Pip calculation matrix V13.1"""
        if 'JPY' in pair:
            return abs(price1 - price2) / 0.01
        elif 'XAUUSD' in pair:
            return abs(price1 - price2) / 0.1
        else:
            return abs(price1 - price2) / 0.0001

    def should_trail(self, pair, pos):
        current_price = self.parse_price_data()[0]
        if not current_price:
            return None

        pips_profit = self.calculate_pips(pair, current_price, pos['entry'])
        
        if pips_profit < 20:
            return None  # Stage 1 not reached

        # Stage 1: Breakeven +2 pips
        if pos['sl'] < pos['entry'] + 0.0002 and pips_profit >= 20:
            return {'sl': pos['entry'] + 0.0002, 'stage': 'BREAKEVEN'}

        # Stage 2: Dynamic Trailing
        if pips_profit >= 40:
            trail_step = 0.0004 if pips_profit < 100 else 0.0002
            new_sl = current_price - trail_step * (1 if pos['type'] == 'BUY' else -1)
            if new_sl > pos['sl']:
                return {'sl': new_sl, 'stage': 'TRAILING', 'pips': pips_profit}

        return None

    def check_reversal_exit(self, pair):
        """Emergency exit if breach EMA21 M15 opposite direction"""
        try:
            with open(EMA_DATA_PATH, 'r') as f:
                ema_line = f.read().strip()
                ema21 = float(ema_line.split('|')[1])  # pair|ema21|trend
            current_price = self.parse_price_data()[0]
            
            pos = self.positions.get(pair)
            if not pos:
                return False

            # Close if price breaches EMA21 impulsively opposite to position
            if pos['type'] == 'BUY' and current_price < ema21 * 0.999:
                return True
            if pos['type'] == 'SELL' and current_price > ema21 * 1.001:
                return True
        except:
            pass
        return False

    async def write_modify_order(self, pair, new_sl):
        with open(MODIFY_ORDERS_PATH, 'w') as f:
            f.write(f"{pair}|MODIFY_SL|{new_sl}\n")
        logger.info(f"Trailing SL updated: {pair} -> {new_sl}")

    async def write_close_order(self, pair, reason):
        with open(CLOSE_ORDERS_PATH, 'a') as f:
            f.write(f"{pair}|CLOSE|{reason}\n")
        await self.send_telegram(f"🚨 EMERGENCY CLOSE: {pair} - {reason}")
        logger.warning(f"Emergency close: {pair} - {reason}")

    async def check_drawdown_lock(self):
        balance, equity = self.parse_account_stats()
        if equity < self.daily_peak_equity * 0.95:  # 5% drawdown
            for pair in self.positions:
                await self.write_close_order(pair, "DRAWDOWN_LOCK")
            await self.send_telegram(f"🔒 DRAWDOWN LOCK ACTIVATED: {equity:.2f} ({((self.daily_peak_equity-equity)/self.daily_peak_equity*100):.1f}%)")
            return True
        return False

    async def monitor_loop(self):
        logger.info("SAC-MONITOR-V13.1 started (1s loop)")
        while True:
            try:
                # Parse data
                stats_line = open(ACCOUNT_STATS_PATH).read().strip()
                self.parse_account_stats()
                self.parse_positions(stats_line)

                # Drawdown check first
                if await self.check_drawdown_lock():
                    time.sleep(60)  # Cooldown
                    continue

                # Per position checks
                for pair, pos in self.positions.items():
                    trail_update = self.should_trail(pair, pos)
                    if trail_update:
                        await self.write_modify_order(pair, trail_update['sl'])
                        await self.send_telegram(f"✅ {trail_update['stage']}: {pair} SL={trail_update['sl']:.5f} ({trail_update.get('pips',0):.1f}p)")
                    
                    if self.check_reversal_exit(pair):
                        await self.write_close_order(pair, "EMA21_REVERSAL")

                time.sleep(1)  # 1s loop

            except Exception as e:
                logger.error(f"Monitor error: {e}")
                time.sleep(5)

if __name__ == "__main__":
    import sys
    monitor = SACMonitor()
    if len(sys.argv) > 1 and sys.argv[1] == 'monitor':
        asyncio.run(monitor.monitor_loop())
    else:
        print("Usage: python3 realtime_monitor.py monitor")